version: "3.8"

services:
  mysql_db:
    container_name: hackathon_db
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/x86_64
    tty: true
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    volumes:
      - type: volume
        source: hackathon_mysql
        target: /var/lib/mysql
      - type: bind
        source: ./init
        target: /docker-entrypoint-initdb.d

volumes:
  hackathon_mysql:
    name: hackathon_mysql
